-- ERROR ---------------------------------------- examples/err/src/e81.erlt:17:1
Spec mismatch for access_map/1
Specified:  `fun((#( id :: A, location :: B, C )) -> #( id :: A, location :: B ))`
Elaborated: `fun((#( id :: A, location :: B )) -> #( id :: A, location :: B ))`
 17| -spec access_map(#(id :: Id, location :: Location, _)) -> #(id :: Id, location :: Location).
...| ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
