bad_shapes.erlt:23:33: field a already defined for this shape type
%   23| -spec test() -> #(a::integer(), a::float()).
%     |                                 ^^^^^^^^^^

bad_shapes.erlt:25:34: field id already defined for this shape type
%   25| -type my_map(A, B) :: #(id :: A, id :: B).
%     |                                  ^^^^^^^

bad_shapes.erlt:28:11: field a used more than once in the same shape
%   28|     #(a=1,a=2).
%     |           ^^^

bad_shapes.erlt:30:13: field a used more than once in the same shape
%   30| test(#(a=X, a=Y)) ->
%     |             ^^^

