enum_fields.erlt:9:45: field a already defined in enum duplicate.variant
%    9| -enum duplicate :: (variant{a :: integer(), a :: integer()}).
%     |                                             ^^^^^^^^^^^^^^

enum_fields.erlt:13:9: no fields defined for enum enum.no_fields
%   13|         enum.no_fields{},
%     |         ^^^^^^^^^^^^^^^^

enum_fields.erlt:14:9: expected fields for enum enum.variant
%   14|         enum.variant,
%     |         ^^^^^^^^^^^^

enum_fields.erlt:14:9: field b of enum enum.variant has no initializer or default value
%   14|         enum.variant,
%     |         ^^^^^^^^^^^^

enum_fields.erlt:15:9: field b of enum enum.variant has no initializer or default value
%   15|         enum.variant{},
%     |         ^^^^^^^^^^^^^^

enum_fields.erlt:16:9: field b of enum enum.variant has no initializer or default value
%   16|         enum.variant{a = 10},
%     |         ^^^^^^^^^^^^^^^^^^^^

enum_fields.erlt:17:31: field does_not_exist undefined in enum enum.variant
%   17|         enum.variant{b = 1.0, does_not_exist = 10},
%     |                               ^^^^^^^^^^^^^^^^^^^

enum_fields.erlt:18:22: field does_not_exist undefined in enum enum.variant
%   18|         enum.variant{does_not_exist = _} = enum.variant{b = 1.0}
%     |                      ^^^^^^^^^^^^^^^^^^

enum_fields.erlt:21:31: field a already defined in enum enum.variant
%   21| duplicate(enum.variant{a = 1, a = 2, b = 3}) ->
%     |                               ^^^^^

enum_fields.erlt:22:25: field a already defined in enum enum.variant
%   22|     enum.variant{a = 1, a = 2, b = 3}.
%     |                         ^^^^^

enum_fields.erlt:9:1: type duplicate() is unused
%    9| -enum duplicate :: (variant{a :: integer(), a :: integer()}).
%     | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

