redefine_type.erlt:21:1: type foo already defined
%   21| -opaque foo(T) :: {T}.
%     | ^^^^^^^^^^^^^^^^^^^^^

redefine_type.erlt:24:1: defined a new type with the same name: node as a pre-defined type
%   24| -type node(A,B) :: {A,B}.
%     | ^^^^^^^^^^^^^^^^^^^^^^^^

redefine_type.erlt:26:1: defined a new enum with the same name: list as a pre-defined type
%   26| -enum list(A,B) :: (first{A}, second{B}, nil).
%     | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

