shadow_var.erlt:36:12: variable 'Y' is already bound - must write '^Y' to use value in pattern
%   36|     {'ok', Y} = X,
%     |            ^

shadow_var.erlt:38:16: variable 'Y' is already bound - must write '^Y' to use value in pattern
%   38|         {'ok', Y} -> true;
%     |                ^

shadow_var.erlt:51:10: variable 'Y' is already bound - must write '^Y' to use value in pattern
%   51|         {Y} -> true
%     |          ^

shadow_var.erlt:56:19: variable 'Y' is already bound - must write '^Y' to use value in pattern
%   56|         #str{id = Y} -> true
%     |                   ^

shadow_var.erlt:61:18: variable 'Y' is already bound - must write '^Y' to use value in pattern
%   61|         ab.a{a = Y} -> true
%     |                  ^

shadow_var.erlt:68:15: type variable 'A' is only used once (is unbound)
%   68| -spec g(_X, [{A,B}]) -> [B].
%     |               ^

