struct_positional.erlt:19:37: positional field defined after labelled fields
%   19| -struct invalid :: (a :: integer(), float()).
%     |                                     ^^^^^^^

struct_positional.erlt:27:9: 0 positional fields provided when 1 expected in struct struct
%   27|         #struct{a = 10, 1.0},
%     |         ^^^^^^^^^^^^^^^^^^^^

struct_positional.erlt:27:25: positional field defined after labelled fields
%   27|         #struct{a = 10, 1.0},
%     |                         ^^^

struct_positional.erlt:28:9: 0 positional fields provided when 1 expected in struct struct
%   28|         #struct{a = 10},
%     |         ^^^^^^^^^^^^^^^

struct_positional.erlt:29:22: 2 positional fields provided when 1 expected in struct struct
%   29|         #struct{1.0, 1.0, a = 10},
%     |                      ^^^

struct_positional.erlt:31:9: field b of struct struct2 has no initializer or default value
%   31|         #struct2{1.0, a = 1, 10}
%     |         ^^^^^^^^^^^^^^^^^^^^^^^^

struct_positional.erlt:31:30: positional field defined after labelled fields
%   31|         #struct2{1.0, a = 1, 10}
%     |                              ^^

struct_positional.erlt:19:1: type invalid() is unused
%   19| -struct invalid :: (a :: integer(), float()).
%     | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

