%% generated by rpctc header
-behaviour(gen_server).

-export([equal/1, closer/2, inc/1, dec/1]).

-export([handle_equal/2, handle_closer/3, handle_inc/2, handle_dec/2]).

-export([handle_call/3, handle_cast/2, init/1]).

-include("stdt.hrl").

-callback handle_init(input()) -> state().
-callback handle_equal(integer(), state()) -> {boolean(), state()}.
-callback handle_closer(integer(), integer(), state()) -> {integer(), state()}.
-callback handle_inc(integer(), state()) -> state().
-callback handle_dec(integer(), state()) -> state().

-spec service_start(registration(), input()) -> ok_value(pid()).
service_start(Registration, InitArgs) ->
    RAtom =
        case Registration of
            registration.local{} -> local;
            registration.global{} -> global
        end,
    {ok, Pid} = gen_server:start_link({RAtom, ?MODULE}, ?MODULE, InitArgs, []),
    ok_value.ok{Pid}.

-spec service_stop() -> ok().
service_stop() ->
    ok = gen_server:stop(?MODULE),
    ok.ok{}.

-spec equal(integer()) -> boolean().
equal(Arg0) ->
    gen_server:call(?MODULE, {handle_equal, Arg0}).

-spec closer(integer(), integer()) -> integer().
closer(Arg0, Arg1) ->
    gen_server:call(?MODULE, {handle_closer, Arg0, Arg1}).

-spec inc(integer()) -> ok().
inc(Arg0) ->
    ok = gen_server:cast(?MODULE, {handle_inc, Arg0}),
    ok.ok{}.

-spec dec(integer()) -> ok().
dec(Arg0) ->
    ok = gen_server:cast(?MODULE, {handle_dec, Arg0}),
    ok.ok{}.

-spec init(input()) -> atom_ok_value(state()).
init(InitState) ->
    State = handle_init(InitState),
    {ok, State}.

%% -spec handle_cast
%%     ({handle_inc, integer()}, state()) -> noreply(state());
%%     ({handle_dec, integer()}, state()) -> noreply(state()).
handle_cast({handle_inc, Arg0}, State) ->
    {noreply, (?MODULE:handle_inc)(Arg0, State)};
handle_cast({handle_dec, Arg0}, State) ->
    {noreply, (?MODULE:handle_dec)(Arg0, State)}.

%% -spec handle_call
%%     ({handle_equal, integer()}, pid(), state()) -> reply(boolean(), state());
%%     ({handle_closer, integer(), integer()}, pid(), state()) -> reply(integer(), state()).
handle_call({handle_equal, Arg0}, _From, State) ->
    {Result, NewState} = (?MODULE:handle_equal)(Arg0, State),
    {reply, Result, NewState};
handle_call({handle_closer, Arg0, Arg1}, _From, State) ->
    {Result, NewState} = (?MODULE:handle_closer)(Arg0, Arg1, State),
    {reply, Result, NewState}.
