%% generated by rpctc gadtheader
-behaviour(gen_server).

-export([equal/1, closer/2, inc/1, dec/1]).

-export([handle_equal/2, handle_closer/3, handle_inc/2, handle_dec/2]).

-export([handle_call/3, handle_cast/2, init/1]).

-callback handle_init(input()) -> state().
-callback handle_equal(integer(), state()) -> {boolean(), state()}.
-callback handle_closer(integer(), integer(), state()) -> {integer(), state()}.
-callback handle_inc(integer(), state()) -> state().
-callback handle_dec(integer(), state()) -> state().

%% This is an enum that approximates the GADT below
-enum call_request() ::
    equal{integer()}
    | closer{integer(), integer()}.

%% This generalized enum, that properly types handle_call
%% -genum call_request(Result) :: {
%%     equal(integer()) -> call_request(boolean()),
%%     closer(integer(), integer()) -> call_request(integer())
%% }.
%% Waiting on https://github.com/WhatsApp/erlt/issues/269 to uncomment this.

-enum cast_request() ::
    inc{integer()}
    | dec{integer()}.

-spec service_start(atom, input()) -> {ok, pid()} | ignore | {error, term()}.
service_start(Registration, InitArgs) ->
    gen_server:start_link({Registration, ?MODULE}, ?MODULE, InitArgs, []).

-spec service_stop() -> ok.
service_stop() ->
    gen_server:stop(?MODULE).

-spec equal(integer()) -> boolean().

equal(Arg0) ->
    gen_server:call(?MODULE, call_request.equal{Arg0}).

-spec closer(integer(), integer()) -> integer().

closer(Arg0, Arg1) ->
    gen_server:call(?MODULE, call_request.closer{Arg0, Arg1}).

-spec inc(integer()) -> ok.

inc(Arg0) ->
    gen_server:cast(?MODULE, cast_request.inc{Arg0}).

-spec dec(integer()) -> ok.

dec(Arg0) ->
    gen_server:cast(?MODULE, cast_request.dec{Arg0}).

-spec init(input()) -> {ok, state()}.
init(InitState) ->
    State = handle_init(InitState),
    {ok, State}.

-spec handle_cast(cast_request(), state()) -> {noreply, state()}.

handle_cast(cast_request.inc{Arg0}, State) ->
    {noreply, (?MODULE:handle_inc)(Arg0, State)};
handle_cast(cast_request.dec{Arg0}, State) ->
    {noreply, (?MODULE:handle_dec)(Arg0, State)}.

%% This is what the spec would like with a GADT
%% -spec handle_call(call_request(Result), pid(), state()) -> {reply, Result, state()}.
-spec handle_call(call_request(), pid(), state()) -> {reply, term(), state()}.

handle_call(call_request.equal{Arg0}, _From, State) ->
    {Result, NewState} = (?MODULE:handle_equal)(Arg0, State),
    {reply, Result, NewState};
handle_call(call_request.closer{Arg0, Arg1}, _From, State) ->
    {Result, NewState} = (?MODULE:handle_closer)(Arg0, Arg1, State),
    {reply, Result, NewState}.
