# erlbuild.mk parameters -- see documentation in ../../erlbuild/erlbuild.mk
ERLC_FLAGS := -Wall +debug_info #-Werror

# optional explicit sources -- so that we could exclude parts that don't compile yet
SOURCES := mod01.erl mod02.erl depends_test.erl mod03.erl mod04.erl


include ../../erl2.mk
