all:
	$(MAKE) -C dev/src
	$(MAKE) -C elm-core/src

clean:
	$(MAKE) -C dev/src clean
	$(MAKE) -C elm-core/src clean

hard-clean:
	$(MAKE) -C dev/src hard-clean
	$(MAKE) -C elm-core/src hard-clean

ir:
	$(MAKE) -C dev/src ir
	$(MAKE) -C elm-core/src ir

test-ir:
	$(MAKE) -C dev/src test-ir
	$(MAKE) -C elm-core/src test-ir

update-ir-spec:
	$(MAKE) -C dev/src update-ir-spec
	$(MAKE) -C elm-core/src update-ir-spec
