# erlbuild.mk parameters -- see documentation in ../../erlbuild/erlbuild.mk
ERLC_FLAGS := -Wall +debug_info #-Werror

# exclude sources that don't compile
EXCLUDE_SOURCES := dict.erl dict_ffi.erl

include ../../../erl2.mk
