# erlbuild.mk parameters -- see documentation in ../../erlbuild/erlbuild.mk
ERLC_FLAGS := -Wall +debug_info #-Werror

# optional explicit sources -- so that we could exclude parts that don't compile yet
SOURCES := basics.erl tuple.erl maybe.erl result.erl list.erl dict_ffi.erl dict.erl

include ../../../erl2.mk
