name: ErlT CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Erlang version
        run:  "erl -eval 'erlang:display(erlang:system_info(otp_release)), halt().'  -noshell"
      - name: check formatting
        run:  rebar3 fmt --check || (echo "please run 'rebar3 fmt --write'" && $(exit 1))
      - name: test
        run:  cd ./examples && make test
