name: ErlT CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Erlang version
        run:  "erl -eval 'erlang:display(erlang:system_info(otp_release)), halt().'  -noshell"
      - name: check formatting
        run:  rebar3 fmt --check || (echo "please run 'rebar3 fmt --write'" && $(exit 1))
      - name: erltc and erlbuild
        run:  rebar3 compile
      - name: "compile examples/calc"
        run: "cd ./examples && rebar3 erlt calc"
      - name: "compile examples/dev"
        run: "cd ./examples && rebar3 erlt dev"
      - name: "compile examples/dev_dots"
        run: "cd ./examples && rebar3 erlt dev_dots"
      - name: "compile examples/dev_enum"
        run: "cd ./examples && rebar3 erlt dev_enum"
      - name: "compile examples/dev_struct"
        run: "cd ./examples && rebar3 erlt dev_struct"
      - name: "compile examples/doc"
        run: "cd ./examples && rebar3 erlt doc"
      - name: "compile examples/elm_core"
        run: "cd ./examples && rebar3 erlt elm_core"
      - name: "test-ir for examples/calc"

        run: "cd ./examples && make test-ir/calc"
      - name: "test-ir for examples/dev"
        run: "cd ./examples && make test-ir/dev"
      - name: "test-ir for examples/dev_dots"
        run: "cd ./examples && make test-ir/dev_dots"
      - name: "test-ir for examples/dev_enum"
        run: "cd ./examples && make test-ir/dev_enum"
      - name: "test-ir for examples/dev_struct"
        run: "cd ./examples && make test-ir/dev_struct"
      - name: "test-ir for examples/doc"
        run: "cd ./examples && make test-ir/doc"
      - name: "test-ir for examples/elm_core"
        run: "cd ./examples && make test-ir/elm_core"

