name: StErlang CI

on:
  push:
    paths:
      - 'sterlang/**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Run tests
      run: cd sterlang; sbt test it:test
