name: StErlang CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Erlang version
      run:  "erl -eval 'erlang:display(erlang:system_info(otp_release)), halt().'  -noshell"
    - name: make erl2c
      run:  make -C erl2c/src
    - name: Run tests
      run: cd sterlang; sbt test it:test
