name: StErlang CI

on: [push]

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Java
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Erlang version
      run:  "erl -eval 'erlang:display(erlang:system_info(otp_release)), halt().'  -noshell"
    - name: assembly sterlang.jar
      run: cd sterlang; sbt assembly
    - name: upload sterlang.jar
      uses: actions/upload-artifact@v2
      with:
        name: sterlang.jar
        path: 'sterlang/target/scala-2.13/sterlang.jar'
    - name: 'Setup GraalVM Environment'
      uses: DeLaGuardo/setup-graalvm@2.0
      with:
        graalvm-version: '20.1.0.java11'
    - name: 'Install Native Image Plugin'
      run: gu install native-image
    - name: Build sterlang native for Linux
      run: |
        native-image --no-server --no-fallback -O4 -jar sterlang/target/scala-2.13/sterlang.jar sterlang-linux
    - uses: actions/upload-artifact@v2
      with:
        name: sterlang-linux
        path: sterlang-linux
  mac:
    needs: [ubuntu]
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v1
    - name: Setup Java 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: 'Setup GraalVM Environment'
      uses: DeLaGuardo/setup-graalvm@2.0
      with:
        graalvm-version: '20.1.0.java11'
    - name: 'Install Native Image Plugin'
      run: gu install native-image
    - name: 'Get JAR Artifact'
      uses: actions/download-artifact@v2
      with:
        name: sterlang.jar
    - name: ls
      run: ls -lah
    - name: Build sterlang native for Mac
      run: |
        native-image --no-server --no-fallback -O4 -jar sterlang.jar sterlang-mac
    - uses: actions/upload-artifact@v2
      with:
        name: sterlang-mac
        path: sterlang-mac
